engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
    - config/**
    - lib/**
    - "**.rb"
exclude_paths:
  - spec/**/*
