language: ruby
rvm:
  - 2.3.1
before_install: gem install bundler -v 1.13.6
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
after_success:
  - CODECLIMATE_REPO_TOKEN=fccc18f8d93ac8f23dcb8673a20e9074b927b696aebbb6e2e5afe8ba7ed73e47 bundle exec codeclimate-test-reporter
services:
  - postgresql
env:
  global:
    - RACK_ENV=test
    - DATABASE_URL=postgres://postgresql@localhost:5432/travis_ci_test
