version: '2'

services:
  pg-master:
    env_file:
      - .env
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local
